import type { Metadata } from 'next';
import { buildAbsoluteUrl } from '@/lib/site';
import ScriptGeneratorPageClient from '@/components/tools/ScriptGeneratorPageClient';
import { FileText } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';
import RelatedTools from '@/components/RelatedTools';
export const metadata: Metadata = {
  twitter: {
    card: 'summary_large_image',
    title: 'Free YouTube Script Generator',
    description: 'Generate structured, high-retention YouTube video script outlines instantly. Get hook scripts, B-roll cues, and CTA placements tailored to your niche.',
    images: [buildAbsoluteUrl('/banner.png')],
  },
  title: 'Free YouTube Script Generator',
  description:
    'Generate structured, high-retention YouTube video script outlines instantly. Get hook scripts, B-roll cues, and CTA placements tailored to your niche.',
  openGraph: {
    title: 'Free YouTube Script Generator',
    description:
      'Generate structured, high-retention YouTube video script outlines instantly. Get hook scripts, B-roll cues, and CTA placements.',
    url: buildAbsoluteUrl('/youtube-script-generator'),
    type: 'website',
    images: [
      {
        url: buildAbsoluteUrl('/banner.png'),
        width: 1200,
        height: 630,
        alt: 'FreeViralKit',
      },
    ],
  },
  alternates: {
    canonical: buildAbsoluteUrl('/youtube-script-generator'),
  },
  keywords: [
    'youtube script generator',
    'free youtube script writer',
    'ai youtube script generator',
    'youtube video outline maker',
    'youtube hook generator',
    'how to write a youtube script',
    'youtube script template',
    'youtube video structure',
    'youtube script AI',
  ],
};
const faqItems = [
  {
    question: 'How long should my YouTube script be?',
    answer:
      'The length of your script depends on your target video duration and your speaking pace. A good rule of thumb is that the average person speaks about 130-150 words per minute. Therefore, a 5-minute video script should be roughly 650-750 words. However, instead of obsessing over word count, focus on pacing and structure — ensuring there are no long, boring segments where the viewer might click away.',
  },
  {
    question: 'Should I read my YouTube script word-for-word?',
    answer:
      'For most creators, no. Reading a script word-for-word (especially if you aren\'t using a teleprompter) often sounds robotic and unnatural. The best approach is to use a bullet-point outline (like the ones generated by our tool). Memorize or read a single bullet point, deliver that line naturally to the camera, and then edit the pauses out later. This preserves your authentic tone while keeping you on topic.',
  },
  {
    question: 'What is the most important part of a YouTube script?',
    answer:
      'The Hook (the first 3 to 15 seconds) is indisputably the most important part of your script. If you fail to capture the viewer\'s attention immediately, they will leave before seeing the rest of your video. Your hook must instantly confirm that the viewer is in the right place, tease the value they will get, and create an information gap that forces them to keep watching.',
  },
  {
    question: 'How do I script a Call-To-Action (CTA) without sounding annoying?',
    answer:
      'The secret to a good CTA is tying it to the value of the video. Don\'t just say "Subscribe!" in the first 30 seconds. Instead, place your CTA in the middle of the video right after you have delivered a massive piece of value. Say something like, "If you found that tip helpful, I make videos like this every week, so hit subscribe to catch the next one." This frames the subscription as a benefit to the viewer, not a favor to you.',
  },
  {
    question: 'What is a "B-Roll Cue" in a video script?',
    answer:
      'A B-roll cue is a note in your script that tells you (or your editor) what visuals should be on screen while you are speaking. Because YouTube is a visual platform, having "talking head" footage for 10 minutes straight is boring. Scripting your B-roll ahead of time (e.g., [SHOW SCREENSHOT OF GRAPH HERE]) ensures your video remains visually engaging and helps you film exactly what you need.',
  },
  {
    question: 'Can AI completely write my YouTube script for me?',
    answer:
      'AI is an incredible tool for generating structures, outlines, and hooks, but it cannot replace your unique voice and expertise. If you use AI to write a script word-for-word, your video will likely sound generic and lack the personal anecdotes and emotional inflection that build a loyal audience. Use our AI script generator to build the skeleton, and then flesh it out with your own personality.',
  },
];
const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqItems.map((item) => ({
    '@type': 'Question',
    name: item.question,
    acceptedAnswer: {
      '@type': 'Answer',
      text: item.answer,
    },
  })),
};

const softwareJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'YouTube Script Generator',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Any',
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
  },
};

export default function ScriptGeneratorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }}
      />
      <main className="container mx-auto px-6 py-12 max-w-4xl relative z-10 min-h-screen">
        {/* Hero */}
        <section className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-semibold text-purple-400 bg-purple-400/10 border border-purple-400/20 mb-6 uppercase tracking-wider">
            <FileText className="w-4 h-4" /> AI Script Outline Writer
          </div>
          <h1 className="font-display text-3xl md:text-5xl font-extrabold leading-tight tracking-tight mb-4"> Free YouTube Video Script Outline Generator </h1>
          <p className="text-slate-600 dark:text-slate-400 text-lg max-w-2xl mx-auto">
            Generate structured, high-retention script outlines for your videos. Complete with hook lines, B-roll recommendations, and loops.
          </p>
        </section>
        <ScriptGeneratorPageClient />
        {/* SEO Content */}
        <section className="mt-16 space-y-12">
          <div>
            <h2 className="font-display text-3xl md:text-4xl font-bold mb-6 text-slate-900 dark:text-white">
              Why Great YouTube Videos Always Start With a Structured Script Outline
            </h2>
            <div className="text-slate-600 dark:text-slate-400 leading-relaxed space-y-6 text-lg">
              <p>
                The biggest difference between an amateur YouTube channel that struggles to get 100 views and a professional channel driving millions of impressions isn&apos;t the camera gear, the lighting, or the editing software — it is entirely based on the underlying structure of the videos. When inexperienced creators turn on the camera and simply "wing it," the final result is almost universally rambling, repetitive, and horribly paced. On a platform where the algorithm relentlessly, ruthlessly measures <strong className="text-slate-900 dark:text-white">Audience Retention</strong> and <strong className="text-slate-900 dark:text-white">Average View Duration (AVD)</strong>, a poorly paced, unstructured video is an absolute death sentence for your organic reach.
              </p>

              <p>
                Writing a script — or at the very least, a highly detailed bullet-point outline — solves this structural problem before you even hit record. It forces you to organize your thoughts logically, aggressively trim the fat, and consciously design specific moments that continually re-engage the viewer&apos;s attention. By using a <strong className="text-slate-900 dark:text-white">free YouTube script generator</strong>, you completely bypass the intimidating paralysis of the blank page. Instead, you instantly receive a proven, high-retention framework mathematically tailored to your specific video topic.
              </p>
              <p>
                Our AI doesn&apos;t just spit out generic blocks of text like ChatGPT might if you gave it a lazy prompt. It meticulously builds a structural skeleton designed specifically for the modern YouTube format. It includes psychological hooks designed to minimize viewer drop-off in the first 30 seconds, visual B-roll cues to keep the edit dynamic, precise pacing recommendations, and strategic transition points that carry the viewer effortlessly from one segment to the next.
              </p>
            </div>
          </div>
          <div>
            <h2 className="font-display text-3xl font-bold mb-6 text-slate-900 dark:text-white">
              The 4 Unbreakable Pillars of a High-Retention YouTube Script
            </h2>
            <div className="text-slate-600 dark:text-slate-400 leading-relaxed space-y-6 text-lg">
              <p>
                If you study any viral YouTube video, regardless of the niche, you will find that it follows a surprisingly similar underlying structure. Whether you are filming a high-end tech review, an energetic gaming let&apos;s play, or a calm educational tutorial, mastering these four foundational script pillars will dramatically and permanently improve your channel&apos;s metrics.
              </p>
              <h3 className="font-display text-2xl font-bold text-slate-900 dark:text-white pt-4">
                1. The High-Stakes Hook (0:00 - 0:15)
              </h3>
              <p>
                The first 15 seconds of your video dictate the algorithmic success of the entire upload. Viewers click your thumbnail with a specific, fragile expectation. Your hook must immediately, aggressively validate that expectation. If your title is &quot;How to Fix a Leaky Faucet in 3 Minutes,&quot; do not spend 30 seconds introducing yourself or playing a loud, animated 3D logo sequence. Start the video by immediately showing the leaky faucet, looking at the camera, and saying, &quot;This leak is costing you $100 a month in water bills, and I am going to show you exactly how to fix it in the next 3 minutes using one tool.&quot; Establish the stakes, make the promise, and move on.
              </p>

              <h3 className="font-display text-2xl font-bold text-slate-900 dark:text-white pt-4">
                2. The Body & Aggressive Visual Pacing
              </h3>
              <p>
                The middle of your video is a dangerous zone where viewer attention naturally sags and drifts. To combat this biological reality, your script must be broken into clear, distinct, highly digestible segments. More importantly, your script must include <strong className="text-slate-900 dark:text-white">Visual Pacing cues</strong>. In modern YouTube editing, you should plan to change the visual stimulus on the screen every 3 to 5 seconds. This could be a stark camera angle change, a text pop-up reinforcing your point, a sound effect, or relevant B-roll footage. Our script outline generator automatically suggests these visual pattern interrupts directly in the text to ensure you film enough coverage to keep the viewer&apos;s eye active.
              </p>
              <h3 className="font-display text-2xl font-bold text-slate-900 dark:text-white pt-4">
                3. The Strategic, Value-Driven Call to Action (CTA)
              </h3>
              <p>
                Asking viewers to subscribe at the very beginning of the video is a rookie mistake; it rarely works because you haven&apos;t provided any value to earn their trust yet. Asking at the very end is equally ineffective because most viewers have already clicked away the moment they sense the video is wrapping up. The optimal, mathematically proven place for a CTA is the <strong className="text-slate-900 dark:text-white">Mid-Roll</strong> — immediately after you have delivered a massive &quot;Aha!&quot; moment, solved a major problem, or delivered a highly entertaining sequence. The viewer is currently feeling grateful and entertained, making them exponentially more likely to hit the subscribe button when you briefly ask.
              </p>
              <h3 className="font-display text-2xl font-bold text-slate-900 dark:text-white pt-4">
                4. The Seamless Outro Loop
              </h3>
              <p>
                Never, under any circumstances, say the words, &quot;Well, that is all for today,&quot; &quot;In conclusion,&quot; or &quot;Thanks for watching.&quot; These phrases are lethal poison to your analytics. They act as psychological triggers that explicitly tell the viewer to click off the video before your end screen elements even appear, tanking your final retention numbers and destroying your chances of driving binge sessions. Instead, use an &quot;Outro Loop.&quot; Transition seamlessly from your final educational point directly into pitching your next video without taking a breath. For example: &quot;Now that you know how to fix the faucet, you need to make sure your pipes don&apos;t freeze this winter, which is exactly what I show you how to prevent in this video right here on screen.&quot;
              </p>
            </div>
          </div>
          <div>
            <h2 className="font-display text-3xl font-bold mb-6 text-slate-900 dark:text-white">
              Why Bullet-Point Outlines Destroy Word-For-Word Scripts
            </h2>
            <div className="text-slate-600 dark:text-slate-400 leading-relaxed space-y-6 text-lg">
              <p>
                A massive, critical mistake new creators make when scripting is writing a gigantic block of text and trying to read it perfectly on camera, line by line. Unless you are a professionally trained actor or a news anchor with a high-end teleprompter setup, this almost always results in a stiff, robotic, soulless performance. The creator&apos;s eyes dart back and forth reading off a screen, destroying eye contact, and they sound like they are reading an essay rather than talking <strong className="italic">to</strong> a friend.
              </p>
              <p>
                Our AI script generation tool is specifically calibrated to avoid this trap. It deliberately generates <strong className="text-slate-900 dark:text-white">structured, punchy outlines rather than verbatim essays</strong>. By providing the core talking points, the required visual cues, and the transition markers, the tool gives you the safety net and structural integrity of a professional script while simultaneously forcing you to use your own natural vocabulary, cadence, and emotion to connect the dots. This hybrid approach ensures your video is perfectly structured for the algorithm while fully retaining the authentic, human personality that builds a loyal community.
              </p>
            </div>
          </div>
          {/* Checklist */}
          <div className="glass-card rounded-2xl p-8 border-t-4 border-t-purple-400">
            <h3 className="font-display text-2xl font-bold mb-6 text-slate-900 dark:text-white">
              The Pre-Filming Script Audit Checklist
            </h3>
            <p className="text-slate-600 dark:text-slate-400 mb-6 text-lg">Never hit the record button until your script passes every single one of these checks:</p>
            <ul className="space-y-4 text-slate-600 text-lg">
              <li className="flex items-start gap-3"><span className="mt-2 w-2 h-2 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Does the hook actively deliver on the exact promise made by the title/thumbnail within the first 10 seconds?</span></li>
              <li className="flex items-start gap-3"><span className="mt-2 w-2 h-2 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Are there explicit B-roll cues or visual change notes planned at least every 15-20 seconds to prevent visual fatigue?</span></li>
              <li className="flex items-start gap-3"><span className="mt-2 w-2 h-2 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Is the primary Call-To-Action (CTA) strategically placed immediately after a moment of high value, rather than at the very beginning?</span></li>
              <li className="flex items-start gap-3"><span className="mt-2 w-2 h-2 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Does the script intentionally avoid wrapping up, and instead end abruptly with a compelling pitch to click another specific video (The Outro Loop)?</span></li>
              <li className="flex items-start gap-3"><span className="mt-2 w-2 h-2 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Have you read the entire outline out loud while standing up to ensure the phrasing sounds natural and not like written prose?</span></li>
            </ul>
          </div>
          {/* Related Blog Posts */}
          <div>
            <h2 className="font-display text-2xl font-bold mb-6 text-slate-900 dark:text-white">
              Master the Art of Video Retention
            </h2>
            <div className="grid sm:grid-cols-2 gap-4">
              <Link
                href="/blog/youtube-script-outline-formula"
                className="glass-card rounded-xl p-6 hover:border-purple-400/40 transition-colors group"
              >
                <h3 className="font-semibold text-slate-900 dark:text-white group-hover:text-purple-400 transition-colors mb-2 text-lg">
                  The Viral YouTube Script Outline Formula
                </h3>
                <p className="text-slate-500 dark:text-slate-400">
                  Break down the exact script templates used by top creators to hold attention.
                </p>
              </Link>
              <Link
                href="/blog/increase-youtube-audience-retention"
                className="glass-card rounded-xl p-6 hover:border-purple-400/40 transition-colors group"
              >
                <h3 className="font-semibold text-slate-900 dark:text-white group-hover:text-purple-400 transition-colors mb-2 text-lg">
                  How to Increase YouTube Audience Retention
                </h3>
                <p className="text-slate-500 dark:text-slate-400">
                  Techniques for editing and scripting to keep viewers watching until the end.
                </p>
              </Link>
              <Link
                href="/youtube-hook-generator"
                className="glass-card rounded-xl p-6 hover:border-purple-400/40 transition-colors group"
              >
                <h3 className="font-semibold text-slate-900 dark:text-white group-hover:text-purple-400 transition-colors mb-2 text-lg">
                  YouTube Hook Generator →
                </h3>
                <p className="text-slate-500 dark:text-slate-400">
                  Need a stronger opening? Generate high-retention 15-second hooks.
                </p>
              </Link>
              <Link
                href="/youtube-chapter-generator"
                className="glass-card rounded-xl p-6 hover:border-purple-400/40 transition-colors group"
              >
                <h3 className="font-semibold text-slate-900 dark:text-white group-hover:text-purple-400 transition-colors mb-2 text-lg">
                  YouTube Chapter Generator →
                </h3>
                <p className="text-slate-500 dark:text-slate-400">
                  Convert your script outline segments into YouTube timestamps.
                </p>
              </Link>
            </div>
          </div>
          {/* FAQ Section */}
          <div>
            <h2 className="font-display text-3xl font-bold mb-8 text-slate-900 dark:text-white">
              Frequently Asked Questions
            </h2>
            <div className="space-y-4">
              {faqItems.map((item, index) => (
                <details
                  key={index}
                  className="glass-card rounded-xl group"
                >
                  <summary className="cursor-pointer px-6 py-5 font-semibold text-slate-900 dark:text-white select-none list-none flex items-center justify-between gap-4 text-lg">
                    {item.question}
                    <span className="text-purple-400 text-2xl leading-none group-open:rotate-45 transition-transform">+</span>
                  </summary>
                  <div className="px-6 pb-6 text-slate-600 dark:text-slate-400 leading-relaxed text-lg border-t border-slate-100 dark:border-slate-800 pt-4 mt-2">
                    {item.answer}
                  </div>
                </details>
              ))}
            </div>
          </div>
          {/* Bottom CTA */}
          <div className="glass-card rounded-3xl p-10 text-center mt-12 bg-gradient-to-br from-purple-500/10 via-pink-500/5 to-transparent border border-purple-500/20 shadow-2xl">
            <h3 className="font-display text-2xl md:text-3xl font-bold mb-4 text-slate-900 dark:text-white">
              Your script is ready. Now maximize your reach.
            </h3>
            <p className="text-slate-600 dark:text-slate-400 mb-8 text-lg max-w-2xl mx-auto">
              A perfect script won&apos;t get views if nobody clicks on it. Make sure your video is fully optimized for YouTube search with our all-in-one suite of SEO tools.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link href="/" className="inline-flex items-center gap-3 btn-primary rounded-xl px-8 py-4 font-bold text-lg shadow-lg shadow-purple-500/25 transition-transform hover:scale-105">
                Try Full SEO Optimizer →
              </Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
