import type { Metadata } from 'next';
import { buildAbsoluteUrl } from '@/lib/site';
import ScriptGeneratorPageClient from '@/components/tools/ScriptGeneratorPageClient';
import { FileText } from 'lucide-react';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Free YouTube Script Generator — AI Video Outline Maker',
  description:
    'Generate structured, high-retention YouTube video script outlines instantly. Get hook scripts, B-roll cues, and CTA placements tailored to your niche.',
  openGraph: {
    title: 'Free YouTube Script Generator — AI Video Outline Maker',
    description:
      'Generate structured, high-retention YouTube video script outlines instantly. Get hook scripts, B-roll cues, and CTA placements.',
    url: buildAbsoluteUrl('/youtube-script-generator'),
    type: 'website',
  },
  alternates: {
    canonical: buildAbsoluteUrl('/youtube-script-generator'),
  },
  keywords: [
    'youtube script generator',
    'free youtube script writer',
    'ai youtube script generator',
    'youtube video outline maker',
    'youtube hook generator',
    'how to write a youtube script',
    'youtube script template',
    'youtube video structure',
    'youtube script AI',
  ],
};

const faqItems = [
  {
    question: 'How long should my YouTube script be?',
    answer:
      'The length of your script depends on your target video duration and your speaking pace. A good rule of thumb is that the average person speaks about 130-150 words per minute. Therefore, a 5-minute video script should be roughly 650-750 words. However, instead of obsessing over word count, focus on pacing and structure — ensuring there are no long, boring segments where the viewer might click away.',
  },
  {
    question: 'Should I read my YouTube script word-for-word?',
    answer:
      'For most creators, no. Reading a script word-for-word (especially if you aren\'t using a teleprompter) often sounds robotic and unnatural. The best approach is to use a bullet-point outline (like the ones generated by our tool). Memorize or read a single bullet point, deliver that line naturally to the camera, and then edit the pauses out later. This preserves your authentic tone while keeping you on topic.',
  },
  {
    question: 'What is the most important part of a YouTube script?',
    answer:
      'The Hook (the first 3 to 15 seconds) is indisputably the most important part of your script. If you fail to capture the viewer\'s attention immediately, they will leave before seeing the rest of your video. Your hook must instantly confirm that the viewer is in the right place, tease the value they will get, and create an information gap that forces them to keep watching.',
  },
  {
    question: 'How do I script a Call-To-Action (CTA) without sounding annoying?',
    answer:
      'The secret to a good CTA is tying it to the value of the video. Don\'t just say "Subscribe!" in the first 30 seconds. Instead, place your CTA in the middle of the video right after you have delivered a massive piece of value. Say something like, "If you found that tip helpful, I make videos like this every week, so hit subscribe to catch the next one." This frames the subscription as a benefit to the viewer, not a favor to you.',
  },
  {
    question: 'What is a "B-Roll Cue" in a video script?',
    answer:
      'A B-roll cue is a note in your script that tells you (or your editor) what visuals should be on screen while you are speaking. Because YouTube is a visual platform, having "talking head" footage for 10 minutes straight is boring. Scripting your B-roll ahead of time (e.g., [SHOW SCREENSHOT OF GRAPH HERE]) ensures your video remains visually engaging and helps you film exactly what you need.',
  },
  {
    question: 'Can AI completely write my YouTube script for me?',
    answer:
      'AI is an incredible tool for generating structures, outlines, and hooks, but it cannot replace your unique voice and expertise. If you use AI to write a script word-for-word, your video will likely sound generic and lack the personal anecdotes and emotional inflection that build a loyal audience. Use our AI script generator to build the skeleton, and then flesh it out with your own personality.',
  },
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqItems.map((item) => ({
    '@type': 'Question',
    name: item.question,
    acceptedAnswer: {
      '@type': 'Answer',
      text: item.answer,
    },
  })),
};

export default function ScriptGeneratorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      <main className="container mx-auto px-6 py-12 max-w-4xl relative z-10 min-h-screen">
        {/* Hero */}
        <section className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-semibold text-purple-400 bg-purple-400/10 border border-purple-400/20 mb-6 uppercase tracking-wider">
            <FileText className="w-4 h-4" /> AI Script Outline Writer
          </div>
          <h1 className="font-display text-3xl md:text-5xl font-extrabold leading-tight tracking-tight mb-4">
            Free YouTube <span className="text-gradient">Video Script Outline Generator</span>
          </h1>
          <p className="text-slate-600 dark:text-slate-400 text-lg max-w-2xl mx-auto">
            Generate structured, high-retention script outlines for your videos. Complete with hook lines, B-roll recommendations, and loops.
          </p>
        </section>

        <ScriptGeneratorPageClient />

        {/* SEO Content */}
        <section className="mt-16 space-y-10">
          <div>
            <h2 className="font-display text-2xl md:text-3xl font-bold mb-4 text-slate-900 dark:text-white">
              Why Great YouTube Videos Start With a Script Outline
            </h2>
            <div className="text-slate-600 dark:text-slate-400 leading-relaxed space-y-4">
              <p>
                The biggest difference between an amateur YouTube channel and a professional one isn&apos;t the camera gear or the lighting — it is the structure of the videos. When creators turn on the camera and simply "wing it," the result is often rambling, repetitive, and poorly paced. On a platform where the algorithm relentlessly measures <strong className="text-slate-900 dark:text-white">Audience Retention</strong> and <strong className="text-slate-900 dark:text-white">Average View Duration (AVD)</strong>, a poorly paced video is a death sentence for your reach.
              </p>
              <p>
                Writing a script — or at least a highly detailed outline — solves this problem. It forces you to organize your thoughts logically, trim the fat, and consciously design moments that re-engage the viewer&apos;s attention. By using a <strong className="text-slate-900 dark:text-white">free YouTube script generator</strong>, you bypass the intimidating blank page and instantly get a proven, high-retention framework tailored to your specific topic.
              </p>
              <p>
                Our AI doesn&apos;t just spit out generic paragraphs. It builds a structural skeleton designed specifically for the YouTube format, complete with visual cues, precise pacing recommendations, and psychological hooks designed to minimize viewer drop-off.
              </p>
            </div>
          </div>

          <div>
            <h2 className="font-display text-2xl font-bold mb-4 text-slate-900 dark:text-white">
              The 4 Pillars of a High-Retention YouTube Script
            </h2>
            <div className="text-slate-600 dark:text-slate-400 leading-relaxed space-y-4">
              <p>
                Every viral YouTube video follows a surprisingly similar underlying structure. Whether it is a tech review, a gaming let&apos;s play, or an educational tutorial, mastering these four pillars will dramatically improve your video metrics.
              </p>

              <h3 className="font-display text-xl font-bold text-slate-900 dark:text-white pt-2">
                1. The Hook (0:00 - 0:15)
              </h3>
              <p>
                The first 15 seconds of your video dictate the success of the entire upload. Viewers click your thumbnail with a specific expectation. Your hook must immediately validate that expectation. If your title is "How to Fix a Leaky Faucet," do not spend 30 seconds introducing yourself or playing an animated logo sequence. Start the video by showing the leaky faucet and saying, "This leak is costing you $100 a month, and I am going to show you how to fix it in 3 minutes." Establish the stakes, make the promise, and move on.
              </p>

              <h3 className="font-display text-xl font-bold text-slate-900 dark:text-white pt-2">
                2. The Body & Visual Pacing
              </h3>
              <p>
                The middle of your video is where viewer attention naturally sags. To combat this, your script must be broken into clear, distinct segments. More importantly, your script must include <strong className="text-slate-900 dark:text-white">Visual Pacing cues</strong>. You should plan to change the visual on the screen every 3 to 5 seconds. This could be a camera angle change, a text pop-up, a sound effect, or B-roll footage. Our script generator automatically suggests these visual pattern interrupts to keep the viewer&apos;s eye active.
              </p>

              <h3 className="font-display text-xl font-bold text-slate-900 dark:text-white pt-2">
                3. The Strategic Call to Action (CTA)
              </h3>
              <p>
                Asking viewers to subscribe at the very beginning of the video rarely works because you haven&apos;t provided any value yet. Asking at the very end is also ineffective because most viewers have already clicked away. The optimal place for a CTA is the <strong className="text-slate-900 dark:text-white">Mid-Roll</strong> — immediately after you have delivered a massive "Aha!" moment or a highly entertaining sequence. The viewer is feeling grateful and entertained, making them much more likely to hit the subscribe button.
              </p>

              <h3 className="font-display text-xl font-bold text-slate-900 dark:text-white pt-2">
                4. The Outro Loop
              </h3>
              <p>
                Never say the words, "Well, that is all for today," or "In conclusion." These phrases trigger the viewer to click off the video before your end screen even appears, tanking your final retention numbers. Instead, use an "Outro Loop." Transition seamlessly from your final point directly into pitching your next video. "Now that you know how to fix the faucet, you need to make sure your pipes don&apos;t freeze this winter, which is exactly what I show you in this video right here."
              </p>
            </div>
          </div>

          <div>
            <h2 className="font-display text-2xl font-bold mb-4 text-slate-900 dark:text-white">
              Why Bullet-Point Outlines Beat Word-For-Word Scripts
            </h2>
            <div className="text-slate-600 dark:text-slate-400 leading-relaxed space-y-4">
              <p>
                A common mistake new creators make is writing a massive block of text and trying to read it perfectly on camera. This almost always results in a stiff, robotic performance where the creator is clearly reading off a screen rather than talking <strong className="italic">to</strong> the audience.
              </p>
              <p>
                Our AI script tool deliberately generates <strong className="text-slate-900 dark:text-white">structured outlines rather than verbatim essays</strong>. By providing the core talking points, the required visual cues, and the transition markers, the tool gives you the safety net of a script while forcing you to use your own natural vocabulary to connect the dots. This hybrid approach ensures your video is perfectly structured while retaining your authentic, human personality.
              </p>
            </div>
          </div>

          {/* Checklist */}
          <div>
            <h3 className="font-display text-xl font-bold mb-3 text-slate-900 dark:text-white">
              Pre-Filming Script Checklist
            </h3>
            <ul className="space-y-2 text-slate-600">
              <li className="flex items-start gap-2"><span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Does the hook deliver on the promise of the title/thumbnail within 10 seconds?</span></li>
              <li className="flex items-start gap-2"><span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Are there B-roll or visual change notes at least every 15-20 seconds?</span></li>
              <li className="flex items-start gap-2"><span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Is the CTA placed after a moment of high value, not at the beginning?</span></li>
              <li className="flex items-start gap-2"><span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Does the script end abruptly with a pitch to another video (Outro Loop)?</span></li>
              <li className="flex items-start gap-2"><span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-purple-400 shrink-0" /><span className="dark:text-slate-300">Did you read the outline out loud to ensure it sounds natural?</span></li>
            </ul>
          </div>

          {/* Related Blog Posts */}
          <div>
            <h2 className="font-display text-2xl font-bold mb-4 text-slate-900 dark:text-white">
              Master the Art of Video Retention
            </h2>
            <div className="grid sm:grid-cols-2 gap-4">
              <Link
                href="/blog/youtube-script-outline-formula"
                className="glass-card rounded-xl p-5 hover:border-purple-400/40 transition-colors group"
              >
                <h3 className="font-semibold text-slate-900 dark:text-white group-hover:text-purple-400 transition-colors mb-1">
                  The Viral YouTube Script Outline Formula
                </h3>
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  Break down the exact script templates used by top creators to hold attention.
                </p>
              </Link>
              <Link
                href="/blog/increase-youtube-audience-retention"
                className="glass-card rounded-xl p-5 hover:border-purple-400/40 transition-colors group"
              >
                <h3 className="font-semibold text-slate-900 dark:text-white group-hover:text-purple-400 transition-colors mb-1">
                  How to Increase YouTube Audience Retention
                </h3>
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  Techniques for editing and scripting to keep viewers watching until the end.
                </p>
              </Link>
              <Link
                href="/youtube-hook-generator"
                className="glass-card rounded-xl p-5 hover:border-purple-400/40 transition-colors group"
              >
                <h3 className="font-semibold text-slate-900 dark:text-white group-hover:text-purple-400 transition-colors mb-1">
                  YouTube Hook Generator →
                </h3>
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  Need a stronger opening? Generate high-retention 15-second hooks.
                </p>
              </Link>
              <Link
                href="/youtube-chapter-generator"
                className="glass-card rounded-xl p-5 hover:border-purple-400/40 transition-colors group"
              >
                <h3 className="font-semibold text-slate-900 dark:text-white group-hover:text-purple-400 transition-colors mb-1">
                  YouTube Chapter Generator →
                </h3>
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  Convert your script outline segments into YouTube timestamps.
                </p>
              </Link>
            </div>
          </div>

          {/* FAQ Section */}
          <div>
            <h2 className="font-display text-2xl font-bold mb-6 text-slate-900 dark:text-white">
              Frequently Asked Questions
            </h2>
            <div className="space-y-4">
              {faqItems.map((item, index) => (
                <details
                  key={index}
                  className="glass-card rounded-xl group"
                >
                  <summary className="cursor-pointer px-6 py-4 font-semibold text-slate-900 dark:text-white select-none list-none flex items-center justify-between gap-4">
                    {item.question}
                    <span className="text-purple-400 text-xl leading-none group-open:rotate-45 transition-transform">+</span>
                  </summary>
                  <div className="px-6 pb-5 text-slate-600 dark:text-slate-400 leading-relaxed">
                    {item.answer}
                  </div>
                </details>
              ))}
            </div>
          </div>

          {/* Bottom CTA */}
          <div className="glass-card rounded-2xl p-6 text-center">
            <p className="text-slate-600 dark:text-slate-400 mb-4">Your script is ready. Now make sure your video is discoverable in search.</p>
            <div className="flex flex-wrap justify-center gap-3">
              <Link href="/" className="inline-flex items-center gap-2 btn-primary rounded-xl px-6 py-3 font-semibold">
                Try Full SEO Optimizer →
              </Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
