import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — FreeViralKit',
  description: 'Read the FreeViralKit terms of service. Understand the rules and guidelines for using our free YouTube SEO tool.',
  alternates: { canonical: 'https://freeviralkit.com/terms' },
};

export default function TermsPage() {
  return (
    <main className="container mx-auto px-6 py-12 max-w-3xl relative z-10 min-h-screen">
      <h1 className="font-display text-3xl md:text-4xl font-extrabold mb-4 tracking-tight">Terms of Service</h1>
      <p className="text-slate-500 text-sm mb-8">Last updated: May 7, 2026</p>

      <div className="space-y-8 text-slate-700 leading-relaxed">
        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
          <p>By accessing and using FreeViralKit (freeviralkit.com), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">2. Description of Service</h2>
          <p>FreeViralKit is a free, AI-powered tool that generates YouTube video titles, descriptions, hashtags, tags, and pinned comments. The Service is provided &quot;as is&quot; without warranties of any kind.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">3. Acceptable Use</h2>
          <p className="mb-3">You agree NOT to:</p>
          <ul className="space-y-2 ml-4">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to reverse engineer, decompile, or hack the Service</li>
            <li>Use automated bots or scrapers to access the Service</li>
            <li>Generate content that violates YouTube&apos;s Community Guidelines</li>
            <li>Overload the Service with excessive requests</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">4. AI-Generated Content</h2>
          <p>Content generated by FreeViralKit is AI-generated and provided for informational purposes. You are responsible for reviewing and editing all generated content before using it on YouTube. We do not guarantee that generated content will result in views, subscribers, or rankings.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">5. Intellectual Property</h2>
          <p>You retain ownership of any content you create using our tool. The FreeViralKit brand, logo, and website design are our intellectual property.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">6. Limitation of Liability</h2>
          <p>FreeViralKit shall not be liable for any indirect, incidental, special, or consequential damages arising from the use of our Service, including but not limited to loss of revenue, rankings, or channel performance.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">7. Advertising</h2>
          <p>Our Service displays third-party advertisements through Google AdSense. We are not responsible for the content of these advertisements.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">8. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-bold text-slate-900 mb-3">9. Contact</h2>
          <p>Questions about these Terms? Visit our <a href="/contact" className="text-purple-400 hover:underline">contact page</a>.</p>
        </section>
      </div>
    </main>
  );
}
